dist: trusty

language: python

branches:
  only:
  - master
  - next

python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'

addons:
  apt:
    packages:
      - python-dev
      - python3-dev
      - openmpi-bin
      - libopenmpi-dev

before_install:
  - pip install -r requirements.txt

install:
  - pip install .

script:
  - cd tests/ && mpiexec -np 2 py.test
